package git

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// CreateWorktree creates a git worktree at targetDir on the given branch.
// Handles three cases: local branch exists, remote branch exists, or new branch.
func CreateWorktree(repoDir, targetDir, branch string) error {
	// 1. Local branch exists
	if refExists(repoDir, "refs/heads/"+branch) {
		return run(repoDir, "worktree", "add", targetDir, branch)
	}

	// 2. Remote branch exists
	if refExists(repoDir, "refs/remotes/origin/"+branch) {
		return run(repoDir, "worktree", "add", "--track", "-b", branch, targetDir, "origin/"+branch)
	}

	// 3. Create new branch from HEAD
	return run(repoDir, "worktree", "add", "-b", branch, targetDir)
}

// RemoveWorktree removes a git worktree. Falls back to force removal.
func RemoveWorktree(repoDir, worktreeDir string) error {
	err := run(repoDir, "worktree", "remove", worktreeDir, "--force")
	if err != nil {
		// Fallback: just remove the directory and let git prune later
		return run(repoDir, "worktree", "prune")
	}
	return nil
}

// WriteWorktreeExcludes writes info/exclude patterns to the worktree's git dir
// so that runtime files (.logs/, .pids/, .slot-meta.yml, .env.overrides) don't
// appear in git status.
func WriteWorktreeExcludes(worktreeDir string) error {
	cmd := exec.Command("git", "-C", worktreeDir, "rev-parse", "--git-dir")
	out, err := cmd.Output()
	if err != nil {
		return fmt.Errorf("finding git dir: %w", err)
	}

	gitDir := strings.TrimSpace(string(out))
	// If gitDir is relative, resolve it from the worktree directory
	if !filepath.IsAbs(gitDir) {
		gitDir = filepath.Join(worktreeDir, gitDir)
	}

	excludeDir := filepath.Join(gitDir, "info")
	if err := os.MkdirAll(excludeDir, 0755); err != nil {
		return fmt.Errorf("creating info dir: %w", err)
	}

	excludePath := filepath.Join(excludeDir, "exclude")
	patterns := `# Worktree runtime files (auto-generated by wt create)
.logs/
.pids/
.slot-meta.yml
**/.env.overrides
`
	// Append to existing excludes if present
	existing, _ := os.ReadFile(excludePath)
	if len(existing) > 0 && !strings.Contains(string(existing), ".slot-meta.yml") {
		if !strings.HasSuffix(string(existing), "\n") {
			patterns = "\n" + patterns
		}
		patterns = string(existing) + patterns
	} else if len(existing) == 0 {
		// Write fresh
	} else {
		return nil // Already has our patterns
	}

	return os.WriteFile(excludePath, []byte(patterns), 0644)
}

// PruneWorktrees cleans up stale worktree references.
func PruneWorktrees(repoDir string) {
	exec.Command("git", "-C", repoDir, "worktree", "prune").Run()
}

func refExists(repoDir, ref string) bool {
	cmd := exec.Command("git", "-C", repoDir, "show-ref", "--verify", "--quiet", ref)
	return cmd.Run() == nil
}

func run(repoDir string, args ...string) error {
	fullArgs := append([]string{"-C", repoDir}, args...)
	cmd := exec.Command("git", fullArgs...)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("git %v: %w\n%s", args, err, out)
	}
	return nil
}
